name: Perl application

on: [push]

jobs:
  centos7:

    runs-on: ubuntu-latest

    steps:
    - name: checkout dxtoolkit code
      uses: actions/checkout@master

    - name: Set up a Perl container
      #uses: pioro/dxtoolkit@develop
      uses: docker://pioro/dxperlcent7:5.26


    # - name: display
    #   run: |
    #     echo ${HOME}
    #     ls -l /home/runner/work/dxtoolkit/dxtoolkit

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1.0.0
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     draft: true
    #     prerelease: true

    # - name: Upload Release Asset
    #   id: upload-release-asset 
    #   uses: actions/upload-release-asset@v1.0.1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
    #     asset_path: /home/runner/work/dxtoolkit/dxtoolkit/dxtoolkit.tar.gz
    #     asset_name: dxtoolkit.tar.gz
    #     asset_content_type: application/tgz

  ubuntu:

    runs-on: ubuntu-18.04

    steps:
    - name: checkout dxtoolkit code
      uses: actions/checkout@master

    - name: Set up a Perl container
      run: |
        sudo apt-get update
        sudo apt-get install -y libpar-packer-perl 
        sudo apt-get install -y libjson-pp-perl
        sudo apt-get install -y libdate-manip-perl
        sudo apt-get install -y libdatetime-format-dateparse-perl
        sudo apt-get install -y libcrypt-cbc-perl
        sudo apt-get install -y libcrypt-blowfish-perl
        sudo apt-get install -y libtext-csv-perl
        sudo apt-get install -y libtry-tiny-perl
        sudo apt-get install -y libparse-http-useragent-perl
        sudo apt-get install -y libnet-ssleay-perl
        sudo apt-get install -y libio-socket-ssl-perl
        sudo apt-get install -y libfilter-perl
        sudo apt-get install -y libterm-readkey-perl
        sudo apt-get install -y cpanminus
        sudo apt-get install -y make
        sudo apt-get install -y gcc
        sudo apt-get install -y libssl-dev
        sudo apt-get install -y libwww-perl
        sudo cpanm DateTime::Event::Cron::Quartz
        sudo cpanm Log::Syslog::Fast
        sudo cpanm Filter::Crypto::Decrypt

    - name: Compile
      run: |
          mkdir /home/runner/work/dxtoolkit/dxtoolkit/dxtoolkit2
          cd /home/runner/work/dxtoolkit/dxtoolkit/bin
          pp -u -I /home/runner/work/dxtoolkit/dxtoolkit/lib -M Text::CSV_PP -M List::MoreUtils::PP -M Crypt::Blowfish  \
          -F Crypto=dbutils\.pm$ -M Filter::Crypto::Decrypt -o /home/runner/work/dxtoolkit/dxtoolkit/dxtoolkit2/dxtoolkit `ls dx_*.pl | xargs`
          for i in dx_*.pl ; do name=${i%.pl}; ln -s /home/runner/work/dxtoolkit/dxtoolkit/dxtoolkit2/dxtoolkit /home/runner/work/dxtoolkit/dxtoolkit/dxtoolkit2/$name; done
          ls -l /home/runner/work/dxtoolkit/dxtoolkit/dxtoolkit2
          cd /home/runner/work/dxtoolkit/dxtoolkit/
          tar czvf /home/runner/work/dxtoolkit/dxtoolkit/dxtoolkit.tar.gz dxtoolkit2/

  centos6:

    runs-on: ubuntu-latest

    steps:
    - name: checkout dxtoolkit code
      uses: actions/checkout@master

    - name: Set up a Perl container
      #uses: pioro/dxtoolkit@develop
      uses: docker://pioro/dxperlcent6:5.26

  release:
    runs-on: ubuntu-latest
    needs: [centos6, centos7]
    steps:
    - name: Say
      run: |
        echo "HELLO" 
